
# supabase/config.toml
[functions.create-nowpayments-invoice]
verify_jwt = true

[functions.nowpayments-ipn]
verify_jwt = false

[functions.get-alatpay-config]
verify_jwt = true

[functions.create-alatpay-transaction]
verify_jwt = true

[functions.alatpay-webhook]
verify_jwt = false
