
# supabase/config.toml
[functions.create-nowpayments-invoice]
verify_jwt = true

[functions.nowpayments-ipn]
verify_jwt = false

[functions.klasha-webhook]
verify_jwt = false

[functions.get-klasha-config]
verify_jwt = true

[functions.startbutton-webhook]
verify_jwt = false

[functions.get-startbutton-config]
verify_jwt = true
