// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbtmecjjqxahsyvdbdif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpidG1lY2pqcXhhaHN5dmRiZGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDk3NTQsImV4cCI6MjA2NTQ4NTc1NH0.CAqpjccWB1xI3e5I6R6uNZZMsdgo0mdPXO_RoLWOf6I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);